import { useEffect, useMemo, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { useAuth } from "../auth/AuthProvider";
import { SelectModal, type SelectOption } from "../components/SelectModal";
import { mobileApi } from "../lib/api";
import { supabase } from "../lib/supabase";
import type { RootStackParamList } from "../navigation/types";
import { colors } from "../theme";

type Props = NativeStackScreenProps<RootStackParamList, "CreateRecord">;
type Values = Record<string, string>;

export function CreateRecordScreen({ route, navigation }: Props) {
  const { profile, activeProgram } = useAuth();
  const key = route.params.featureKey;
  const spec = specs[key];
  const [values, setValues] = useState<Values>(() => ({ ...spec.defaults, program_id: activeProgram?.id ?? "" }));
  const [lookups, setLookups] = useState<Record<string, SelectOption[]>>({});
  const [selecting, setSelecting] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  useEffect(() => { if (!profile) return; void loadLookups(key, profile.organizationId, activeProgram?.id ?? null).then(setLookups); }, [activeProgram?.id, key, profile]);
  const selectOptions = useMemo(() => spec.fields.find((field) => field.name === selecting)?.options ?? lookups[selecting ?? ""] ?? [], [lookups, selecting, spec.fields]);

  async function submit() {
    if (!profile) return;
    const missing = spec.fields.find((field) => field.required && !values[field.name]?.trim());
    if (missing) return Alert.alert("Missing information", `${missing.label} is required.`);
    setSaving(true);
    try {
      const data = Object.fromEntries(Object.entries(values).map(([name, value]) => [name, numericFields.has(name) && value !== "" ? Number(value) : value === "" ? undefined : value]));
      await mobileApi("/admin", { method: "POST", body: JSON.stringify({ organizationId: profile.organizationId, action: spec.action, data }) });
      Alert.alert("Saved", `${spec.singular} was created.`);
      navigation.goBack();
    } catch (error) { Alert.alert("Could not save", error instanceof Error ? error.message : "Unexpected error."); }
    finally { setSaving(false); }
  }

  return <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.title}>New {spec.singular.toLowerCase()}</Text>{spec.fields.map((field) => field.kind === "select" ? <Pressable key={field.name} onPress={() => setSelecting(field.name)} style={styles.select}><View><Text style={styles.label}>{field.label}</Text><Text style={styles.selectValue}>{optionLabel(field.options ?? lookups[field.name], values[field.name]) || `Select ${field.label.toLowerCase()}`}</Text></View><Text style={styles.chevron}>›</Text></Pressable> : <View key={field.name} style={styles.field}><Text style={styles.label}>{field.label}</Text><TextInput autoCapitalize={field.name === "email" ? "none" : "sentences"} keyboardType={numericFields.has(field.name) ? "decimal-pad" : field.name === "email" ? "email-address" : "default"} multiline={field.kind === "textarea"} onChangeText={(value) => setValues((current) => ({ ...current, [field.name]: value }))} placeholder={field.placeholder} placeholderTextColor={colors.muted} style={[styles.input, field.kind === "textarea" && styles.textarea]} value={values[field.name] ?? ""} /></View>)}<Pressable disabled={saving} onPress={() => void submit()} style={[styles.save, saving && styles.disabled]}><Text style={styles.saveText}>{saving ? "Saving…" : "Save"}</Text></Pressable><SelectModal onChange={(value) => selecting && setValues((current) => ({ ...current, [selecting]: value }))} onClose={() => setSelecting(null)} options={selectOptions} title={`Select ${spec.fields.find((field) => field.name === selecting)?.label ?? "option"}`} value={selecting ? values[selecting] : ""} visible={selecting !== null} /></ScrollView>;
}

type Field = { name: string; label: string; kind?: "text" | "textarea" | "select"; required?: boolean; placeholder?: string; options?: SelectOption[] };
type Spec = { singular: string; action: string; defaults: Values; fields: Field[] };
const option = (value: string, label?: string): SelectOption => ({ value, label: label ?? title(value) });
const specs: Record<Props["route"]["params"]["featureKey"], Spec> = {
  programs: { singular: "Program", action: "create_program", defaults: { category: "sport", activity_type: "soccer", status: "active" }, fields: [{ name: "name", label: "Name", required: true }, { name: "category", label: "Category", kind: "select", options: ["sport", "event", "social", "generic"].map((v) => option(v)) }, { name: "activity_type", label: "Activity", kind: "select", options: ["soccer", "cricket", "badminton", "volleyball", "basketball", "picnic", "outdoor-gathering", "generic-event", "generic"].map((v) => option(v)) }, { name: "status", label: "Status", kind: "select", options: ["active", "archived"].map((v) => option(v)) }, { name: "notes", label: "Notes", kind: "textarea" }] },
  seasons: { singular: "Season", action: "create_season", defaults: { status: "draft", price_per_session: "" }, fields: [{ name: "program_id", label: "Program", kind: "select", required: true }, { name: "name", label: "Name", required: true }, { name: "start_date", label: "Start date", placeholder: "YYYY-MM-DD" }, { name: "end_date", label: "End date", placeholder: "YYYY-MM-DD" }, { name: "total_planned_sessions", label: "Planned sessions" }, { name: "price_per_session", label: "Price per session", required: true }, { name: "status", label: "Status", kind: "select", options: ["draft", "active", "archived"].map((v) => option(v)) }, { name: "notes", label: "Notes", kind: "textarea" }] },
  sessions: { singular: "Session", action: "create_session", defaults: { status: "scheduled", session_date: today() }, fields: [{ name: "program_id", label: "Program", kind: "select", required: true }, { name: "season_id", label: "Season", kind: "select", required: true }, { name: "name", label: "Name" }, { name: "session_date", label: "Date", required: true, placeholder: "YYYY-MM-DD" }, { name: "location", label: "Location" }, { name: "start_time", label: "Start time", placeholder: "HH:MM" }, { name: "end_time", label: "End time", placeholder: "HH:MM" }, { name: "price_per_session", label: "Price override" }, { name: "status", label: "Status", kind: "select", options: ["scheduled", "completed", "cancelled"].map((v) => option(v)) }, { name: "notes", label: "Notes", kind: "textarea" }] },
  players: { singular: "Player", action: "create_player", defaults: { status: "active" }, fields: [{ name: "display_name", label: "Display name", required: true }, { name: "phone", label: "Phone" }, { name: "email", label: "Email" }, { name: "status", label: "Status", kind: "select", options: ["active", "inactive"].map((v) => option(v)) }, { name: "preferred_position", label: "Preferred position" }, { name: "notes", label: "Notes", kind: "textarea" }] },
  payments: { singular: "Payment", action: "create_payment", defaults: { payment_date: today(), payment_method: "e-transfer", amount: "" }, fields: [{ name: "program_id", label: "Program", kind: "select", required: true }, { name: "season_id", label: "Season", kind: "select", required: true }, { name: "player_id", label: "Player", kind: "select", required: true }, { name: "session_id", label: "Session", kind: "select" }, { name: "payment_date", label: "Payment date", required: true, placeholder: "YYYY-MM-DD" }, { name: "amount", label: "Amount", required: true }, { name: "sessions_covered", label: "Sessions covered" }, { name: "payment_method", label: "Method", kind: "select", options: ["e-transfer", "cash", "other"].map((v) => option(v)) }, { name: "reference_note", label: "Reference note", kind: "textarea" }] },
  expenses: { singular: "Expense", action: "create_expense", defaults: { expense_date: today(), category: "dome_rent", amount: "" }, fields: [{ name: "program_id", label: "Program", kind: "select" }, { name: "season_id", label: "Season", kind: "select" }, { name: "session_id", label: "Session", kind: "select" }, { name: "expense_date", label: "Expense date", required: true, placeholder: "YYYY-MM-DD" }, { name: "category", label: "Category", kind: "select", options: ["dome_rent", "food", "jersey", "equipment", "other"].map((v) => option(v)) }, { name: "amount", label: "Amount", required: true }, { name: "vendor", label: "Vendor" }, { name: "notes", label: "Notes", kind: "textarea" }] }
};

async function loadLookups(key: string, organizationId: string, programId: string | null) { const output: Record<string, SelectOption[]> = {}; const [{ data: programs }, { data: seasons }, { data: players }, { data: sessions }] = await Promise.all([supabase.from("programs").select("id,name").eq("organization_id", organizationId).eq("status", "active").order("name"), supabase.from("seasons").select("id,name,program_id").eq("organization_id", organizationId).order("start_date", { ascending: false }), supabase.from("players").select("id,display_name").eq("organization_id", organizationId).eq("status", "active").order("display_name"), supabase.from("sessions").select("id,name,session_date,program_id").eq("organization_id", organizationId).order("session_date", { ascending: false })]); output.program_id = (programs ?? []).map((r) => ({ value: r.id, label: r.name })); output.season_id = (seasons ?? []).filter((r) => !programId || r.program_id === programId).map((r) => ({ value: r.id, label: r.name })); output.player_id = (players ?? []).map((r) => ({ value: r.id, label: r.display_name })); output.session_id = (sessions ?? []).filter((r) => !programId || r.program_id === programId).map((r) => ({ value: r.id, label: [r.session_date, r.name].filter(Boolean).join(" · ") })); return output; }
const numericFields = new Set(["total_planned_sessions", "price_per_session", "amount", "sessions_covered"]); function optionLabel(options: SelectOption[] | undefined, value: string) { return options?.find((item) => item.value === value)?.label ?? ""; } function title(value: string) { return value.replaceAll("_", " ").replaceAll("-", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); } function today() { return new Date().toISOString().slice(0, 10); }
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 44, backgroundColor: colors.background }, title: { marginBottom: 18, color: colors.ink, fontSize: 26, fontWeight: "900" }, field: { marginBottom: 13 }, label: { marginBottom: 6, color: colors.ink, fontSize: 12, fontWeight: "800", textTransform: "uppercase" }, input: { minHeight: 50, paddingHorizontal: 14, color: colors.ink, borderWidth: 1, borderColor: colors.line, borderRadius: 12, backgroundColor: colors.surface }, textarea: { minHeight: 96, paddingTop: 14, textAlignVertical: "top" }, select: { minHeight: 62, marginBottom: 13, padding: 13, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderWidth: 1, borderColor: colors.line, borderRadius: 12, backgroundColor: colors.surface }, selectValue: { color: colors.muted }, chevron: { color: colors.pitch, fontSize: 28 }, save: { minHeight: 52, marginTop: 8, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: colors.pitch }, saveText: { color: "white", fontSize: 16, fontWeight: "900" }, disabled: { opacity: 0.5 } });
