import { useCallback, useState } from "react";
import { Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect } from "@react-navigation/native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { useAuth } from "../auth/AuthProvider";
import { LoadingView } from "../components/LoadingView";
import { mobileApi } from "../lib/api";
import { supabase } from "../lib/supabase";
import type { RootStackParamList } from "../navigation/types";
import { colors } from "../theme";

export function FixtureScreen({ route }: NativeStackScreenProps<RootStackParamList, "Fixture">) {
  const { profile } = useAuth(); const [teams, setTeams] = useState<any[]>([]); const [matches, setMatches] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [values, setValues] = useState({ repeats: "1", breakAfterGames: "0", breakLengthMinutes: "0", firstSegmentMinutes: "10", secondSegmentMinutes: "10" });
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); const [teamResult, matchResult] = await Promise.all([supabase.from("session_teams").select("id,name").eq("session_id", route.params.sessionId).order("name"), supabase.from("session_matches").select("id,match_number,scheduled_start_time,scheduled_end_time,result_status,team_a:session_teams!session_matches_team_a_id_fkey(name),team_b:session_teams!session_matches_team_b_id_fkey(name)").eq("session_id", route.params.sessionId).order("match_number")]); const firstError = teamResult.error ?? matchResult.error; if (firstError) setError(firstError.message); else { setTeams(teamResult.data ?? []); setMatches(matchResult.data ?? []); } setLoading(false); setRefreshing(false); }, [route.params.sessionId]); useFocusEffect(useCallback(() => { void load(); }, [load])); if (loading) return <LoadingView error={error} />;
  async function generate() { if (!profile) return; setSaving(true); try { await mobileApi("/sessions", { method: "POST", body: JSON.stringify({ organizationId: profile.organizationId, sessionId: route.params.sessionId, action: "generate_fixture", data: Object.fromEntries(Object.entries(values).map(([key, value]) => [key, Number(value)])) }) }); await load(true); Alert.alert("Generated", "The fixture schedule is ready."); } catch (actionError) { Alert.alert("Could not generate fixture", actionError instanceof Error ? actionError.message : "Unexpected error."); } finally { setSaving(false); } }
  return <ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl onRefresh={() => void load(true)} refreshing={refreshing} tintColor={colors.pitch} />}><View style={styles.form}><Text style={styles.heading}>Generate fixture</Text><Text style={styles.intro}>{teams.length} teams available. Existing unplayed fixtures will be replaced.</Text>{Object.entries(values).map(([key, value]) => <View key={key} style={styles.field}><Text style={styles.label}>{labels[key]}</Text><TextInput keyboardType="number-pad" onChangeText={(next) => setValues((current) => ({ ...current, [key]: next }))} style={styles.input} value={value} /></View>)}<Pressable disabled={saving || teams.length < 2} onPress={() => void generate()} style={[styles.button, (saving || teams.length < 2) && styles.disabled]}><Text style={styles.buttonText}>{saving ? "Generating…" : "Generate fixture"}</Text></Pressable>{error ? <Text style={styles.error}>{error}</Text> : null}</View><Text style={styles.sectionTitle}>Schedule</Text>{matches.length ? matches.map((match) => <View key={match.id} style={styles.match}><Text style={styles.matchTitle}>Game {match.match_number}: {relation(match.team_a)} vs {relation(match.team_b)}</Text><Text style={styles.meta}>{[match.scheduled_start_time, match.scheduled_end_time].filter(Boolean).join(" – ") || "Time not set"} · {match.result_status}</Text></View>) : <Text style={styles.empty}>No fixture generated.</Text>}</ScrollView>;
}
const labels: Record<string, string> = { repeats: "Repeat matchups", breakAfterGames: "Break after games", breakLengthMinutes: "Break minutes", firstSegmentMinutes: "Minutes before break", secondSegmentMinutes: "Minutes after break" }; function relation(value: any) { const row = Array.isArray(value) ? value[0] : value; return row?.name ?? "-"; }
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 40, backgroundColor: colors.background }, form: { padding: 16, borderWidth: 1, borderColor: colors.line, borderRadius: 15, backgroundColor: colors.surface }, heading: { color: colors.ink, fontSize: 21, fontWeight: "900" }, intro: { marginTop: 6, marginBottom: 14, color: colors.muted }, field: { marginBottom: 10 }, label: { marginBottom: 5, color: colors.muted, fontSize: 12, fontWeight: "800", textTransform: "uppercase" }, input: { minHeight: 46, paddingHorizontal: 12, color: colors.ink, borderWidth: 1, borderColor: colors.line, borderRadius: 10 }, button: { minHeight: 49, marginTop: 4, alignItems: "center", justifyContent: "center", borderRadius: 10, backgroundColor: colors.pitch }, buttonText: { color: "white", fontWeight: "900" }, disabled: { opacity: 0.45 }, error: { marginTop: 10, color: colors.danger }, sectionTitle: { marginTop: 22, marginBottom: 10, color: colors.ink, fontSize: 19, fontWeight: "900" }, match: { marginBottom: 9, padding: 14, borderWidth: 1, borderColor: colors.line, borderRadius: 13, backgroundColor: colors.surface }, matchTitle: { color: colors.ink, fontWeight: "900" }, meta: { marginTop: 5, color: colors.muted }, empty: { color: colors.muted } });
