import { useCallback, useLayoutEffect, useState } from "react";
import { Alert, FlatList, Modal, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect } from "@react-navigation/native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { useAuth } from "../auth/AuthProvider";
import { LoadingView } from "../components/LoadingView";
import { mobileApi } from "../lib/api";
import { supabase } from "../lib/supabase";
import type { RootStackParamList } from "../navigation/types";
import { colors } from "../theme";

export function LeaguesScreen({ navigation }: NativeStackScreenProps<RootStackParamList, "Leagues">) { const { profile } = useAuth(); const [rows, setRows] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [formVisible, setFormVisible] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async (refresh = false) => { if (!profile) return; refresh ? setRefreshing(true) : setLoading(true); const { data, error: queryError } = await supabase.from("leagues").select("id,name,status,start_date,end_date,points_for_win,points_for_draw,points_for_loss,league_teams(id),league_matches(id)").eq("organization_id", profile.organizationId).order("created_at", { ascending: false }); if (queryError) setError(queryError.message); else setRows(data ?? []); setLoading(false); setRefreshing(false); }, [profile]); useFocusEffect(useCallback(() => { void load(); }, [load])); useLayoutEffect(() => { navigation.setOptions(profile?.role === "admin" ? { headerRight: () => <Pressable onPress={() => setFormVisible(true)}><Text style={styles.add}>Add</Text></Pressable> } : { headerRight: undefined }); }, [navigation, profile?.role]); if (loading) return <LoadingView error={error} />;
  return <><FlatList contentContainerStyle={styles.content} data={rows} keyExtractor={(item) => item.id} refreshControl={<RefreshControl onRefresh={() => void load(true)} refreshing={refreshing} tintColor={colors.pitch} />} ListEmptyComponent={<Text style={styles.empty}>{error ?? "No leagues."}</Text>} renderItem={({ item }) => <Pressable onPress={() => navigation.navigate("LeagueDetail", { leagueId: item.id })} style={styles.card}><View style={styles.row}><Text style={styles.name}>{item.name}</Text><Text style={styles.status}>{item.status}</Text></View><Text style={styles.meta}>{item.start_date ?? "-"} – {item.end_date ?? "-"}</Text><Text style={styles.meta}>{item.league_teams?.length ?? 0} teams · {item.league_matches?.length ?? 0} fixtures</Text></Pressable>} /><NewLeagueModal onClose={() => setFormVisible(false)} onCreated={async (id) => { setFormVisible(false); await load(true); navigation.navigate("LeagueDetail", { leagueId: id }); }} organizationId={profile!.organizationId} visible={formVisible} /></>;
}
function NewLeagueModal({ visible, organizationId, onClose, onCreated }: { visible: boolean; organizationId: string; onClose(): void; onCreated(id: string): void }) { const [values, setValues] = useState({ name: "", start_date: "", end_date: "", status: "draft", points_for_win: "3", points_for_draw: "1", points_for_loss: "0", notes: "" }); const [saving, setSaving] = useState(false); async function save() { if (!values.name.trim()) return; setSaving(true); try { const result = await mobileApi<{ id: string }>("/leagues", { method: "POST", body: JSON.stringify({ organizationId, action: "create", data: { ...values, start_date: values.start_date || undefined, end_date: values.end_date || undefined, points_for_win: Number(values.points_for_win), points_for_draw: Number(values.points_for_draw), points_for_loss: Number(values.points_for_loss) } }) }); onCreated(result.id); } catch (error) { Alert.alert("Could not create league", error instanceof Error ? error.message : "Unexpected error."); } finally { setSaving(false); } } return <Modal animationType="slide" onRequestClose={onClose} presentationStyle="pageSheet" visible={visible}><ScrollView contentContainerStyle={styles.modal}><View style={styles.modalHeader}><Text style={styles.title}>New league</Text><Pressable onPress={onClose}><Text style={styles.add}>Cancel</Text></Pressable></View>{Object.entries(values).map(([key, value]) => <View key={key} style={styles.field}><Text style={styles.label}>{label(key)}</Text><TextInput keyboardType={key.startsWith("points") ? "number-pad" : "default"} onChangeText={(next) => setValues((current) => ({ ...current, [key]: next }))} placeholder={key.includes("date") ? "YYYY-MM-DD" : undefined} style={styles.input} value={value} /></View>)}<Pressable disabled={saving || !values.name.trim()} onPress={() => void save()} style={styles.save}><Text style={styles.saveText}>{saving ? "Saving…" : "Create league"}</Text></Pressable></ScrollView></Modal>; }
function label(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 40, backgroundColor: colors.background }, add: { color: colors.pitch, fontWeight: "900" }, empty: { padding: 30, color: colors.muted, textAlign: "center" }, card: { marginBottom: 10, padding: 16, borderWidth: 1, borderColor: colors.line, borderRadius: 14, backgroundColor: colors.surface }, row: { flexDirection: "row", justifyContent: "space-between", gap: 10 }, name: { flex: 1, color: colors.ink, fontSize: 17, fontWeight: "900" }, status: { color: colors.pitch, fontWeight: "800", textTransform: "capitalize" }, meta: { marginTop: 6, color: colors.muted }, modal: { padding: 20, paddingBottom: 40, backgroundColor: colors.background }, modalHeader: { marginBottom: 20, flexDirection: "row", justifyContent: "space-between" }, title: { color: colors.ink, fontSize: 26, fontWeight: "900" }, field: { marginBottom: 12 }, label: { marginBottom: 5, color: colors.muted, fontSize: 11, fontWeight: "900", textTransform: "uppercase" }, input: { minHeight: 49, paddingHorizontal: 12, color: colors.ink, borderWidth: 1, borderColor: colors.line, borderRadius: 10, backgroundColor: colors.surface }, save: { minHeight: 51, marginTop: 8, alignItems: "center", justifyContent: "center", borderRadius: 10, backgroundColor: colors.pitch }, saveText: { color: "white", fontWeight: "900" } });
