import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useFocusEffect } from "@react-navigation/native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { useAuth } from "../auth/AuthProvider";
import { LoadingView } from "../components/LoadingView";
import { SelectModal } from "../components/SelectModal";
import { mobileApi } from "../lib/api";
import { supabase } from "../lib/supabase";
import type { RootStackParamList } from "../navigation/types";
import { colors } from "../theme";

type Player = { id: string; name: string }; type Team = { id: string; name: string; players: Player[] }; type Position = { slot: string; label: string; x: number; y: number; playerId?: string; jerseyColor?: string }; type Saved = { session_team_id: string; player_count: number; formation: string; positions: Position[] }; type Picker = "team" | "count" | "formation" | null;
const formations = ["2-1-1", "2-2-1", "2-2-2", "3-3-1", "3-3-2", "3-3-3", "4-3-3"]; const counts = [5, 6, 7, 8, 9, 10, 11]; const jerseyColors = ["#059669", "#DC2626", "#2563EB", "#F59E0B", "#111827", "#FFFFFF"];
export function LineupsScreen({ route }: NativeStackScreenProps<RootStackParamList, "Lineups">) {
  const { profile } = useAuth(); const [teams, setTeams] = useState<Team[]>([]); const [saved, setSaved] = useState<Saved[]>([]); const [teamId, setTeamId] = useState(""); const [playerCount, setPlayerCount] = useState(7); const [formation, setFormation] = useState("3-3-1"); const [positions, setPositions] = useState<Position[]>([]); const [jerseyColor, setJerseyColor] = useState(jerseyColors[0]); const [picker, setPicker] = useState<Picker>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); const [teamResult, lineupResult] = await Promise.all([supabase.rpc("lineup_builder_teams", { p_session_id: route.params.sessionId }), supabase.rpc("lineup_builder_lineups", { p_session_id: route.params.sessionId })]); const firstError = teamResult.error ?? lineupResult.error; if (firstError) setError(firstError.message); else { const nextTeams = (teamResult.data ?? []) as Team[]; setTeams(nextTeams); setSaved((lineupResult.data ?? []) as Saved[]); setTeamId((current) => current || nextTeams[0]?.id || ""); } setLoading(false); }, [route.params.sessionId]); useFocusEffect(useCallback(() => { void load(); }, [load]));
  useEffect(() => { if (!teamId) return; const lineup = saved.find((item) => item.session_team_id === teamId); const team = teams.find((item) => item.id === teamId); const nextCount = lineup?.player_count ?? Math.min(team?.players.length || 7, 11); const nextFormation = lineup?.formation || formationFor(nextCount); setPlayerCount(nextCount); setFormation(nextFormation); setPositions(lineup?.positions?.length ? lineup.positions : defaultPositions(nextFormation, nextCount)); setJerseyColor(lineup?.positions?.[0]?.jerseyColor ?? jerseyColors[0]); }, [saved, teamId, teams]);
  const team = teams.find((item) => item.id === teamId); const assigned = useMemo(() => new Set(positions.map((item) => item.playerId).filter(Boolean)), [positions]); const available = (team?.players ?? []).filter((player) => !assigned.has(player.id)); const options = picker === "team" ? teams.map((item) => ({ value: item.id, label: item.name })) : picker === "count" ? counts.map((count) => ({ value: String(count), label: `${count} players` })) : formations.map((value) => ({ value, label: value })); if (loading) return <LoadingView error={error} />;
  function changeFormation(value: string) { const count = 1 + value.split("-").reduce((sum, item) => sum + Number(item), 0); const template = defaultPositions(value, count); const playerIds = positions.map((item) => item.playerId).filter(Boolean).slice(0, count) as string[]; setFormation(value); setPlayerCount(count); setPositions(template.map((item, index) => ({ ...item, playerId: playerIds[index] }))); }
  function changeCount(value: number) { const nextFormation = formationFor(value); const template = defaultPositions(nextFormation, value); const playerIds = positions.map((item) => item.playerId).filter(Boolean).slice(0, value) as string[]; setPlayerCount(value); setFormation(nextFormation); setPositions(template.map((item, index) => ({ ...item, playerId: playerIds[index] }))); }
  function assign(playerId: string) { const empty = positions.findIndex((item) => !item.playerId); if (empty < 0) return; setPositions((current) => current.map((item, index) => index === empty ? { ...item, playerId } : item)); }
  function remove(playerId: string) { setPositions((current) => current.map((item) => item.playerId === playerId ? { ...item, playerId: undefined } : item)); }
  async function save() { if (!profile || !teamId) return; setSaving(true); try { await mobileApi("/sessions", { method: "POST", body: JSON.stringify({ organizationId: profile.organizationId, sessionId: route.params.sessionId, action: "save_lineup", data: { sessionTeamId: teamId, playerCount, formation, positions: positions.map((item) => ({ ...item, jerseyColor })) } }) }); await load(); Alert.alert("Saved", "Team lineup was saved."); } catch (saveError) { Alert.alert("Could not save lineup", saveError instanceof Error ? saveError.message : "Unexpected error."); } finally { setSaving(false); } }
  return <ScrollView contentContainerStyle={styles.content}><Text style={styles.heading}>Lineup builder</Text>{error ? <Text style={styles.error}>{error}</Text> : null}{teams.length === 0 ? <Text style={styles.empty}>You are not assigned to a team for this session.</Text> : <><View style={styles.controls}><Control label="Team" value={team?.name ?? "Select"} onPress={() => setPicker("team")} /><Control label="Players" value={String(playerCount)} onPress={() => setPicker("count")} /><Control label="Formation" value={formation} onPress={() => setPicker("formation")} /></View><View style={styles.colors}>{jerseyColors.map((color) => <Pressable accessibilityLabel={`Use ${color} jersey`} key={color} onPress={() => setJerseyColor(color)} style={[styles.color, { backgroundColor: color }, jerseyColor === color && styles.colorActive]} />)}</View><View style={styles.field}><View style={styles.halfway} /><View style={styles.circle} />{positions.map((position) => { const player = team?.players.find((item) => item.id === position.playerId); return <Pressable disabled={!player} key={position.slot} onPress={() => player && remove(player.id)} style={[styles.slot, { left: `${position.x}%`, top: `${position.y}%` }, player && { backgroundColor: jerseyColor }]}><Text numberOfLines={2} style={[styles.slotText, jerseyColor === "#FFFFFF" && styles.darkText]}>{player?.name ?? position.label}</Text></Pressable>; })}</View><Text style={styles.subheading}>Available players</Text><View style={styles.players}>{available.map((player) => <Pressable key={player.id} onPress={() => assign(player.id)} style={styles.player}><Text style={styles.playerText}>+ {player.name}</Text></Pressable>)}{!available.length ? <Text style={styles.empty}>All team players are on the field.</Text> : null}</View><Pressable disabled={saving || !teamId} onPress={() => void save()} style={[styles.save, saving && styles.disabled]}><Text style={styles.saveText}>{saving ? "Saving…" : "Save lineup"}</Text></Pressable></>}<SelectModal onChange={(value) => picker === "team" ? setTeamId(value) : picker === "count" ? changeCount(Number(value)) : changeFormation(value)} onClose={() => setPicker(null)} options={options} title={`Select ${picker ?? "option"}`} value={picker === "team" ? teamId : picker === "count" ? String(playerCount) : formation} visible={picker !== null} /></ScrollView>;
}
function Control({ label, value, onPress }: { label: string; value: string; onPress(): void }) { return <Pressable onPress={onPress} style={styles.control}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value} ›</Text></Pressable>; }
function formationFor(count: number) { return count <= 5 ? "2-1-1" : count === 6 ? "2-2-1" : count === 7 ? "3-2-1" : count === 8 ? "3-3-1" : count === 9 ? "3-3-2" : count === 10 ? "3-3-3" : "4-3-3"; }
function defaultPositions(formation: string, count: number): Position[] { const parts = formation.split("-").map(Number); const layers = [{ x: 8, labels: ["GK"] }, ...parts.map((total, index) => ({ x: [30, 58, 84][index] ?? 84, labels: Array.from({ length: total }, (_, player) => `${["D", "M", "F"][index] ?? "P"}${player + 1}`) }))]; const positions = layers.flatMap((layer, layerIndex) => layer.labels.map((label, index) => ({ slot: `${layerIndex}-${index}`, label, x: layer.x, y: ((index + 1) * 100) / (layer.labels.length + 1) }))); return positions.slice(0, count); }
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 44, backgroundColor: colors.background }, heading: { color: colors.ink, fontSize: 24, fontWeight: "900" }, error: { marginTop: 8, color: colors.danger }, controls: { marginTop: 14, flexDirection: "row", gap: 7 }, control: { flex: 1, minHeight: 55, padding: 9, borderWidth: 1, borderColor: colors.line, borderRadius: 10, backgroundColor: colors.surface }, label: { color: colors.muted, fontSize: 10, fontWeight: "900", textTransform: "uppercase" }, value: { marginTop: 5, color: colors.ink, fontWeight: "900" }, colors: { marginVertical: 12, flexDirection: "row", gap: 10 }, color: { width: 34, height: 34, borderRadius: 17, borderWidth: 1, borderColor: colors.line }, colorActive: { borderWidth: 3, borderColor: colors.pitch }, field: { position: "relative", width: "100%", aspectRatio: 10 / 14, overflow: "hidden", borderWidth: 3, borderColor: "rgba(255,255,255,.75)", borderRadius: 14, backgroundColor: "#10B981" }, halfway: { position: "absolute", left: "50%", top: 0, bottom: 0, width: 2, backgroundColor: "rgba(255,255,255,.55)" }, circle: { position: "absolute", left: "37%", top: "41%", width: "26%", aspectRatio: 1, borderWidth: 2, borderColor: "rgba(255,255,255,.6)", borderRadius: 999 }, slot: { position: "absolute", width: 62, minHeight: 38, marginLeft: -31, marginTop: -19, padding: 4, alignItems: "center", justifyContent: "center", borderRadius: 9, borderWidth: 1, borderColor: "rgba(255,255,255,.8)", backgroundColor: "rgba(6,78,59,.35)" }, slotText: { color: "white", fontSize: 10, fontWeight: "900", textAlign: "center" }, darkText: { color: colors.ink }, subheading: { marginTop: 16, color: colors.ink, fontSize: 18, fontWeight: "900" }, players: { marginTop: 9, flexDirection: "row", flexWrap: "wrap", gap: 8 }, player: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 9, backgroundColor: colors.pitchSoft }, playerText: { color: colors.pitch, fontWeight: "800" }, empty: { marginTop: 14, color: colors.muted }, save: { minHeight: 52, marginTop: 18, alignItems: "center", justifyContent: "center", borderRadius: 11, backgroundColor: colors.pitch }, saveText: { color: "white", fontSize: 16, fontWeight: "900" }, disabled: { opacity: 0.5 } });
