import { useCallback, useState } from "react";
import { Alert, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from "react-native";
import { useFocusEffect } from "@react-navigation/native";
import { useAuth } from "../auth/AuthProvider";
import { LoadingView } from "../components/LoadingView";
import { mobileApi } from "../lib/api";
import { supabase } from "../lib/supabase";
import { colors } from "../theme";

type Row = { player_id: string; player_name: string; season_id: string; season_name: string; total_paid_amount: number; estimated_used_amount: number; balance_amount: number; remaining_sessions: number };
export function MyStatusScreen() {
  const { profile, activeProgram } = useAuth(); const [rows, setRows] = useState<Row[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [sending, setSending] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async (refresh = false) => { if (!profile) return; refresh ? setRefreshing(true) : setLoading(true); setError(null); let query: any = supabase.from("player_season_payment_summary").select("*").order("season_name"); if (activeProgram?.id) query = query.eq("program_id", activeProgram.id); if (profile.role === "player" && profile.playerId) query = query.eq("player_id", profile.playerId); const result = await query; if (result.error) setError(result.error.message); else setRows(result.data ?? []); setLoading(false); setRefreshing(false); }, [activeProgram?.id, profile]);
  useFocusEffect(useCallback(() => { void load(); }, [load])); if (loading) return <LoadingView error={error} />;
  async function notify(row: Row) { if (!profile) return; setSending(row.season_id); try { const result = await mobileApi<{ data?: { duplicate?: boolean } }>("/notifications", { method: "POST", body: JSON.stringify({ action: "submit_payment_sent", organizationId: profile.organizationId, playerId: row.player_id, seasonId: row.season_id }) }); Alert.alert(result.data?.duplicate ? "Already sent" : "Admin notified", result.data?.duplicate ? "A pending payment alert already exists." : "Your payment alert was sent to the club admins."); } catch (e) { Alert.alert("Could not notify admins", e instanceof Error ? e.message : "Unexpected error."); } finally { setSending(null); } }
  return <FlatList contentContainerStyle={styles.content} data={rows} keyExtractor={(item) => `${item.player_id}-${item.season_id}`} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={colors.pitch} />} ListEmptyComponent={<Text style={styles.empty}>No payment status is available.</Text>} renderItem={({ item }) => <View style={styles.card}><Text style={styles.player}>{item.player_name}</Text><Text style={styles.season}>{item.season_name}</Text><View style={styles.metrics}><Metric label="Paid" value={item.total_paid_amount} /><Metric label="Used" value={item.estimated_used_amount} /><Metric label="Balance" value={item.balance_amount} /></View><Text style={styles.remaining}>{item.remaining_sessions ?? 0} sessions remaining</Text>{profile?.role === "player" && profile.playerId === item.player_id ? <Pressable disabled={sending === item.season_id} onPress={() => void notify(item)} style={styles.button}><Text style={styles.buttonText}>{sending === item.season_id ? "Sending…" : "I sent my payment"}</Text></Pressable> : null}</View>} />;
}
function Metric({ label, value }: { label: string; value: number }) { return <View><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>${Number(value ?? 0).toFixed(2)}</Text></View>; }
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 40, backgroundColor: colors.background }, card: { marginBottom: 12, padding: 16, borderWidth: 1, borderColor: colors.line, borderRadius: 15, backgroundColor: colors.surface }, player: { color: colors.ink, fontSize: 18, fontWeight: "900" }, season: { marginTop: 3, color: colors.muted }, metrics: { marginTop: 16, flexDirection: "row", justifyContent: "space-between" }, metricLabel: { color: colors.muted, fontSize: 11, fontWeight: "800", textTransform: "uppercase" }, metricValue: { marginTop: 3, color: colors.ink, fontWeight: "900" }, remaining: { marginTop: 12, color: colors.pitch, fontWeight: "800" }, button: { marginTop: 14, minHeight: 46, alignItems: "center", justifyContent: "center", borderRadius: 10, backgroundColor: colors.pitch }, buttonText: { color: "white", fontWeight: "900" }, empty: { padding: 30, color: colors.muted, textAlign: "center" } });
