import { useCallback, useState } from "react";
import { Alert, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from "react-native";
import { useFocusEffect } from "@react-navigation/native";
import { useAuth } from "../auth/AuthProvider";
import { LoadingView } from "../components/LoadingView";
import { mobileApi } from "../lib/api";
import { supabase } from "../lib/supabase";
import { colors } from "../theme";

type Row = { id: string; amount: number; message: string; read_at: string | null; created_at: string; player: any; season: any };
export function NotificationsScreen() {
  const { profile } = useAuth(); const [rows, setRows] = useState<Row[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [accepting, setAccepting] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async (refresh = false) => { if (!profile) return; refresh ? setRefreshing(true) : setLoading(true); setError(null); const { data, error: queryError } = await supabase.from("notifications").select("id,amount,message,read_at,created_at,player:players(display_name),season:seasons(name)").eq("organization_id", profile.organizationId).order("read_at", { ascending: true, nullsFirst: true }).order("created_at", { ascending: false }); if (queryError) setError(queryError.message); else setRows((data ?? []) as Row[]); setLoading(false); setRefreshing(false); }, [profile]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  if (loading) return <LoadingView error={error} />;
  async function accept(id: string) { if (!profile) return; setAccepting(id); try { await mobileApi("/notifications", { method: "POST", body: JSON.stringify({ action: "accept", organizationId: profile.organizationId, notificationId: id }) }); await load(true); } catch (actionError) { Alert.alert("Could not accept", actionError instanceof Error ? actionError.message : "Unexpected error."); } finally { setAccepting(null); } }
  return <FlatList contentContainerStyle={styles.content} data={rows} keyExtractor={(item) => item.id} refreshControl={<RefreshControl onRefresh={() => void load(true)} refreshing={refreshing} tintColor={colors.pitch} />} ListHeaderComponent={<View style={styles.header}><Text style={styles.count}>{rows.filter((row) => !row.read_at).length}</Text><Text style={styles.caption}>unread payment alerts</Text>{error ? <Text style={styles.error}>{error}</Text> : null}</View>} ListEmptyComponent={<Text style={styles.empty}>No notifications.</Text>} renderItem={({ item }) => <View style={[styles.card, !item.read_at && styles.unread]}><View style={styles.row}><Text style={styles.player}>{relation(item.player) ?? "Player"}</Text><Text style={styles.amount}>${Number(item.amount).toFixed(2)}</Text></View><Text style={styles.message}>{item.message}</Text><Text style={styles.meta}>{relation(item.season) ?? "Season"} · {new Date(item.created_at).toLocaleString()}</Text>{!item.read_at ? <Pressable disabled={accepting === item.id} onPress={() => void accept(item.id)} style={styles.button}><Text style={styles.buttonText}>{accepting === item.id ? "Accepting…" : "Accept & record payment"}</Text></Pressable> : <Text style={styles.read}>Accepted</Text>}</View>} />;
}
function relation(value: any) { const row = Array.isArray(value) ? value[0] : value; return row?.display_name ?? row?.name ?? null; }
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 40, backgroundColor: colors.background }, header: { marginBottom: 16 }, count: { color: colors.ink, fontSize: 32, fontWeight: "900" }, caption: { color: colors.muted }, error: { marginTop: 8, color: colors.danger }, card: { marginBottom: 10, padding: 16, borderWidth: 1, borderColor: colors.line, borderRadius: 15, backgroundColor: colors.surface }, unread: { borderColor: "#FDA4AF", backgroundColor: "#FFF1F2" }, row: { flexDirection: "row", justifyContent: "space-between", gap: 12 }, player: { flex: 1, color: colors.ink, fontSize: 16, fontWeight: "900" }, amount: { color: colors.pitch, fontWeight: "900" }, message: { marginTop: 8, color: colors.ink, lineHeight: 20 }, meta: { marginTop: 7, color: colors.muted, fontSize: 12 }, button: { marginTop: 13, minHeight: 45, alignItems: "center", justifyContent: "center", borderRadius: 10, backgroundColor: colors.pitch }, buttonText: { color: "white", fontWeight: "900" }, read: { marginTop: 10, color: colors.muted, fontWeight: "800" }, empty: { padding: 30, color: colors.muted, textAlign: "center" } });
