import { useCallback, useMemo, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect } from "@react-navigation/native";
import { useAuth } from "../auth/AuthProvider";
import { LoadingView } from "../components/LoadingView";
import { mobileApi } from "../lib/api";
import { supabase } from "../lib/supabase";
import { colors } from "../theme";

type Rating = { attacking: string; defending: string; goalkeeping: string; notes: string }; type Player = { id: string; display_name: string; preferred_position: string | null };
export function PerformanceScreen() { const { profile, activeProgram } = useAuth(); const [players, setPlayers] = useState<Player[]>([]); const [ratings, setRatings] = useState<Record<string, Rating>>({}); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!profile || !activeProgram) { setLoading(false); return; } setLoading(true); const [playerResult, ratingResult] = await Promise.all([supabase.from("players").select("id,display_name,preferred_position").eq("organization_id", profile.organizationId).eq("status", "active").order("display_name"), supabase.from("player_performance_ratings").select("player_id,attacking_skill_percent,defending_skill_percent,goalkeeping_skill_percent,notes").eq("organization_id", profile.organizationId).eq("program_id", activeProgram.id)]); const firstError = playerResult.error ?? ratingResult.error; if (firstError) setError(firstError.message); else { setPlayers(playerResult.data ?? []); const map: Record<string, Rating> = {}; for (const player of playerResult.data ?? []) { const saved = (ratingResult.data ?? []).find((item) => item.player_id === player.id); map[player.id] = { attacking: saved?.attacking_skill_percent == null ? "" : String(saved.attacking_skill_percent), defending: saved?.defending_skill_percent == null ? "" : String(saved.defending_skill_percent), goalkeeping: saved?.goalkeeping_skill_percent == null ? "" : String(saved.goalkeeping_skill_percent), notes: saved?.notes ?? "" }; } setRatings(map); } setLoading(false); }, [activeProgram, profile]); useFocusEffect(useCallback(() => { void load(); }, [load])); const visible = useMemo(() => players.filter((player) => `${player.display_name} ${player.preferred_position ?? ""}`.toLowerCase().includes(query.toLowerCase())), [players, query]); if (loading) return <LoadingView error={error} />;
  function setValue(id: string, key: keyof Rating, value: string) { if (key !== "notes" && value && (!/^\d{0,3}$/.test(value) || Number(value) > 100)) return; setRatings((current) => ({ ...current, [id]: { ...current[id], [key]: value } })); }
  async function save() { if (!profile || !activeProgram) return; setSaving(true); try { await mobileApi("/performance", { method: "POST", body: JSON.stringify({ organizationId: profile.organizationId, programId: activeProgram.id, ratings: players.map((player) => ({ playerId: player.id, attacking: numberOrNull(ratings[player.id]?.attacking), defending: numberOrNull(ratings[player.id]?.defending), goalkeeping: numberOrNull(ratings[player.id]?.goalkeeping), notes: ratings[player.id]?.notes.trim() || null })) }) }); Alert.alert("Saved", "Player performance ratings were updated."); } catch (saveError) { Alert.alert("Could not save ratings", saveError instanceof Error ? saveError.message : "Unexpected error."); } finally { setSaving(false); } }
  return <FlatList contentContainerStyle={styles.content} data={visible} keyExtractor={(item) => item.id} ListHeaderComponent={<View><Text style={styles.heading}>{activeProgram?.name ?? "No program"} ratings</Text><TextInput onChangeText={setQuery} placeholder="Filter players" placeholderTextColor={colors.muted} style={styles.search} value={query} />{error ? <Text style={styles.error}>{error}</Text> : null}</View>} ListFooterComponent={activeProgram ? <Pressable disabled={saving} onPress={() => void save()} style={[styles.save, saving && styles.disabled]}><Text style={styles.saveText}>{saving ? "Saving…" : "Save ratings"}</Text></Pressable> : null} renderItem={({ item }) => <View style={styles.card}><Text style={styles.name}>{item.display_name}</Text><Text style={styles.position}>{item.preferred_position ?? "No preferred position"}</Text><View style={styles.ratings}>{(["attacking", "defending", "goalkeeping"] as const).map((key) => <View key={key} style={styles.rating}><Text style={styles.label}>{key}</Text><TextInput keyboardType="number-pad" onChangeText={(value) => setValue(item.id, key, value)} placeholder="—" placeholderTextColor={colors.muted} style={styles.input} value={ratings[item.id]?.[key] ?? ""} /><Text style={styles.percent}>%</Text></View>)}</View><TextInput multiline onChangeText={(value) => setValue(item.id, "notes", value)} placeholder="Notes" placeholderTextColor={colors.muted} style={styles.notes} value={ratings[item.id]?.notes ?? ""} /></View>} />; }
function numberOrNull(value?: string) { return value == null || value === "" ? null : Number(value); }
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 44, backgroundColor: colors.background }, heading: { color: colors.ink, fontSize: 24, fontWeight: "900" }, search: { minHeight: 48, marginVertical: 14, paddingHorizontal: 13, color: colors.ink, borderWidth: 1, borderColor: colors.line, borderRadius: 11, backgroundColor: colors.surface }, error: { marginBottom: 10, color: colors.danger }, card: { marginBottom: 10, padding: 15, borderWidth: 1, borderColor: colors.line, borderRadius: 14, backgroundColor: colors.surface }, name: { color: colors.ink, fontSize: 16, fontWeight: "900" }, position: { marginTop: 3, color: colors.muted, fontSize: 12 }, ratings: { marginTop: 12, flexDirection: "row", gap: 7 }, rating: { flex: 1, position: "relative" }, label: { marginBottom: 5, color: colors.muted, fontSize: 9, fontWeight: "900", textTransform: "uppercase" }, input: { minHeight: 44, paddingHorizontal: 10, paddingRight: 22, color: colors.ink, fontWeight: "900", borderWidth: 1, borderColor: colors.line, borderRadius: 9 }, percent: { position: "absolute", right: 7, bottom: 14, color: colors.muted }, notes: { minHeight: 45, marginTop: 9, padding: 10, color: colors.ink, borderWidth: 1, borderColor: colors.line, borderRadius: 9 }, save: { minHeight: 52, marginTop: 8, alignItems: "center", justifyContent: "center", borderRadius: 11, backgroundColor: colors.pitch }, saveText: { color: "white", fontWeight: "900", fontSize: 16 }, disabled: { opacity: 0.5 } });
