import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { useAuth } from "../auth/AuthProvider";
import { SelectModal } from "../components/SelectModal";
import { mobileApi } from "../lib/api";
import { supabase } from "../lib/supabase";
import type { RootStackParamList } from "../navigation/types";
import { colors } from "../theme";

export function PlayerEditScreen({ route, navigation }: NativeStackScreenProps<RootStackParamList, "PlayerEdit">) {
  const { profile } = useAuth(); const [values, setValues] = useState<Record<string, string>>({ display_name: "", phone: "", email: "", status: "active", preferred_position: "", notes: "" }); const [statusOpen, setStatusOpen] = useState(false); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!profile) return; void supabase.from("players").select("display_name,phone,email,status,preferred_position,notes").eq("id", route.params.playerId).eq("organization_id", profile.organizationId).single().then(({ data, error }) => { if (error) Alert.alert("Could not load player", error.message); else if (data) setValues(Object.fromEntries(Object.entries(data).map(([key, value]) => [key, value == null ? "" : String(value)]))); }); }, [profile, route.params.playerId]);
  const set = (name: string, value: string) => setValues((current) => ({ ...current, [name]: value }));
  async function save() { if (!profile || !values.display_name.trim()) return; setSaving(true); try { await mobileApi("/admin", { method: "POST", body: JSON.stringify({ organizationId: profile.organizationId, action: "update_player", data: { playerId: route.params.playerId, values: Object.fromEntries(Object.entries(values).map(([key, value]) => [key, value === "" ? undefined : value])) } }) }); Alert.alert("Player updated", "The player profile was saved."); navigation.goBack(); } catch (e) { Alert.alert("Could not save player", e instanceof Error ? e.message : "Unexpected error."); } finally { setSaving(false); } }
  return <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">{[{ key: "display_name", label: "Display name" }, { key: "phone", label: "Phone" }, { key: "email", label: "Email" }, { key: "preferred_position", label: "Preferred position" }, { key: "notes", label: "Notes" }].map((field) => <TextInput key={field.key} autoCapitalize={field.key === "email" ? "none" : "sentences"} multiline={field.key === "notes"} onChangeText={(value) => set(field.key, value)} placeholder={field.label} placeholderTextColor={colors.muted} style={[styles.input, field.key === "notes" && styles.notes]} value={values[field.key]} />)}<Pressable onPress={() => setStatusOpen(true)} style={styles.select}><Text style={styles.selectLabel}>Status</Text><Text style={styles.selectValue}>{values.status}</Text></Pressable><Pressable disabled={saving} onPress={() => void save()} style={styles.button}><Text style={styles.buttonText}>{saving ? "Saving…" : "Save changes"}</Text></Pressable><SelectModal onChange={(value) => set("status", value)} onClose={() => setStatusOpen(false)} options={[{ value: "active", label: "Active" }, { value: "inactive", label: "Inactive" }]} title="Player status" value={values.status} visible={statusOpen} /></ScrollView>;
}
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 44, backgroundColor: colors.background }, input: { minHeight: 50, marginBottom: 13, paddingHorizontal: 14, color: colors.ink, borderWidth: 1, borderColor: colors.line, borderRadius: 12, backgroundColor: colors.surface }, notes: { minHeight: 96, paddingTop: 14, textAlignVertical: "top" }, select: { marginBottom: 16, padding: 14, borderWidth: 1, borderColor: colors.line, borderRadius: 12, backgroundColor: colors.surface }, selectLabel: { color: colors.ink, fontSize: 12, fontWeight: "800", textTransform: "uppercase" }, selectValue: { marginTop: 5, color: colors.muted, textTransform: "capitalize" }, button: { minHeight: 52, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: colors.pitch }, buttonText: { color: "white", fontWeight: "900" } });
