import { useCallback, useMemo, useState } from "react";
import { Alert, FlatList, Linking, Pressable, RefreshControl, Share, StyleSheet, Text, View } from "react-native";
import { useFocusEffect } from "@react-navigation/native";
import { useAuth } from "../auth/AuthProvider";
import { LoadingView } from "../components/LoadingView";
import { supabase } from "../lib/supabase";
import { colors } from "../theme";

type Row = { playerId: string; playerName: string; seasonId: string; seasonName: string; amount: number; phone: string; pending: boolean };
const interacEmail = "jahirhstu2@gmail.com"; const appLink = "https://ou-soccer-manager.vercel.app/"; const confirmation = `Confirm payment by clicking the Sent button beside your name in the app. App link: ${appLink}`;
export function RemindersScreen() { const { profile } = useAuth(); const [rows, setRows] = useState<Row[]>([]); const [selected, setSelected] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async (refresh = false) => { if (!profile) return; refresh ? setRefreshing(true) : setLoading(true); const [summaryResult, playerResult, notificationResult] = await Promise.all([supabase.from("player_season_payment_summary").select("player_id,player_name,season_id,season_name,owes_money"), supabase.from("players").select("id,phone").eq("organization_id", profile.organizationId), supabase.rpc("public_payment_notification_keys")]); const firstError = summaryResult.error ?? playerResult.error ?? notificationResult.error; if (firstError) setError(firstError.message); else { const phones = new Map((playerResult.data ?? []).map((player) => [player.id, player.phone ?? ""])); const pending = new Set((notificationResult.data ?? []).map((item: any) => `${item.player_id}:${item.season_id}:${Number(item.amount).toFixed(2)}`)); const next = (summaryResult.data ?? []).map((item: any) => ({ playerId: item.player_id, playerName: item.player_name ?? "Unknown player", seasonId: item.season_id, seasonName: item.season_name ?? "Season", amount: Number(item.owes_money ?? 0), phone: phones.get(item.player_id) ?? "", pending: pending.has(`${item.player_id}:${item.season_id}:${Number(item.owes_money ?? 0).toFixed(2)}`) })).filter((item) => item.amount > 0).sort((a, b) => b.amount - a.amount || a.playerName.localeCompare(b.playerName)); setRows(next); setSelected(next.filter((item) => !item.pending).map(key)); } setLoading(false); setRefreshing(false); }, [profile]); useFocusEffect(useCallback(() => { void load(); }, [load])); const selectedRows = useMemo(() => rows.filter((row) => selected.includes(key(row))), [rows, selected]); if (loading) return <LoadingView error={error} />;
  async function shareGroup() { await Share.share({ message: groupMessage(selectedRows) }); } async function openWhatsApp(row: Row) { const phone = normalizePhone(row.phone); if (!phone) return Alert.alert("No phone number", "Add a phone number to the player profile first."); const url = `https://wa.me/${phone}?text=${encodeURIComponent(personalMessage(row))}`; if (await Linking.canOpenURL(url)) await Linking.openURL(url); else Alert.alert("WhatsApp unavailable", "Could not open WhatsApp on this device."); }
  return <FlatList contentContainerStyle={styles.content} data={rows} keyExtractor={key} refreshControl={<RefreshControl onRefresh={() => void load(true)} refreshing={refreshing} tintColor={colors.pitch} />} ListHeaderComponent={<View style={styles.header}><Text style={styles.heading}>{rows.length} owing</Text><Text style={styles.intro}>{selectedRows.length} selected for the group reminder.</Text><View style={styles.actions}><Pressable onPress={() => setSelected(rows.filter((row) => !row.pending).map(key))} style={styles.secondary}><Text style={styles.secondaryText}>Select all</Text></Pressable><Pressable disabled={!selectedRows.length} onPress={() => void shareGroup()} style={styles.primary}><Text style={styles.primaryText}>Share group draft</Text></Pressable></View>{error ? <Text style={styles.error}>{error}</Text> : null}</View>} ListEmptyComponent={<Text style={styles.empty}>No players currently owe money.</Text>} renderItem={({ item }) => { const active = selected.includes(key(item)); return <View style={[styles.card, active && styles.active]}><View style={styles.row}><Pressable disabled={item.pending} onPress={() => setSelected((current) => active ? current.filter((value) => value !== key(item)) : [...current, key(item)])} style={[styles.check, active && styles.checked]}><Text style={styles.checkText}>{active ? "✓" : ""}</Text></Pressable><View style={styles.player}><Text style={styles.name}>{item.playerName}</Text><Text style={styles.meta}>{item.seasonName} · Owes ${item.amount.toFixed(2)}</Text>{item.pending ? <Text style={styles.pending}>Payment sent pending</Text> : null}</View></View><Text style={styles.message}>{personalMessage(item)}</Text><View style={styles.cardActions}><Pressable onPress={() => void Share.share({ message: personalMessage(item) })} style={styles.secondary}><Text style={styles.secondaryText}>Share</Text></Pressable><Pressable onPress={() => void openWhatsApp(item)} style={styles.primary}><Text style={styles.primaryText}>WhatsApp</Text></Pressable></View></View>; }} />;
}
function key(row: Row) { return `${row.playerId}:${row.seasonId}`; } function groupMessage(rows: Row[]) { if (!rows.length) return "No players selected."; return ["OU Soccer payment reminders:", "", ...rows.map((row) => `- ${row.playerName}: $${row.amount.toFixed(2)}`), "", `Please send Interac to ${interacEmail}.`, confirmation].join("\n"); } function personalMessage(row: Row) { return [`Hi ${row.playerName.trim().split(/\s+/)[0]}, friendly reminder: you currently owe $${row.amount.toFixed(2)} for OU Soccer.`, `Please send Interac to ${interacEmail}.`, confirmation].join("\n\n"); } function normalizePhone(value: string) { const digits = value.replace(/\D/g, ""); return digits.length === 10 ? `1${digits}` : digits; }
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 44, backgroundColor: colors.background }, header: { marginBottom: 15 }, heading: { color: colors.ink, fontSize: 25, fontWeight: "900" }, intro: { marginTop: 5, color: colors.muted }, actions: { marginTop: 12, flexDirection: "row", gap: 8 }, primary: { minHeight: 43, paddingHorizontal: 13, alignItems: "center", justifyContent: "center", borderRadius: 9, backgroundColor: colors.pitch }, primaryText: { color: "white", fontWeight: "900" }, secondary: { minHeight: 43, paddingHorizontal: 13, alignItems: "center", justifyContent: "center", borderRadius: 9, backgroundColor: colors.pitchSoft }, secondaryText: { color: colors.pitch, fontWeight: "900" }, error: { marginTop: 8, color: colors.danger }, empty: { padding: 30, color: colors.muted, textAlign: "center" }, card: { marginBottom: 10, padding: 15, borderWidth: 1, borderColor: colors.line, borderRadius: 14, backgroundColor: colors.surface }, active: { borderColor: colors.pitch }, row: { flexDirection: "row", gap: 10 }, check: { width: 29, height: 29, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.line, borderRadius: 8 }, checked: { borderColor: colors.pitch, backgroundColor: colors.pitch }, checkText: { color: "white", fontWeight: "900" }, player: { flex: 1 }, name: { color: colors.ink, fontSize: 16, fontWeight: "900" }, meta: { marginTop: 4, color: colors.muted }, pending: { marginTop: 5, color: "#B45309", fontSize: 11, fontWeight: "800" }, message: { marginTop: 12, padding: 10, color: colors.ink, lineHeight: 19, borderRadius: 9, backgroundColor: "#F8FAFC" }, cardActions: { marginTop: 10, flexDirection: "row", justifyContent: "flex-end", gap: 8 } });
