import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useAuth } from "../auth/AuthProvider";
import { mobileApi } from "../lib/api";
import { colors } from "../theme";

export function SettingsScreen() {
  const { profile } = useAuth(); const [confirmation, setConfirmation] = useState(""); const [cleaning, setCleaning] = useState(false);
  function confirmCleanup() { if (confirmation.trim() !== "CLEANUP") return Alert.alert("Confirmation required", "Type CLEANUP exactly before continuing."); Alert.alert("Delete club operating data?", "This permanently removes players, seasons, sessions, payments, attendance, teams, goals, leagues, and related records. Login accounts and roles remain.", [{ text: "Cancel", style: "cancel" }, { text: "Delete data", style: "destructive", onPress: () => void cleanup() }]); }
  async function cleanup() { if (!profile) return; setCleaning(true); try { await mobileApi("/admin", { method: "POST", body: JSON.stringify({ organizationId: profile.organizationId, action: "cleanup", data: { confirmation: "CLEANUP" } }) }); setConfirmation(""); Alert.alert("Cleanup complete", "Club operating data was removed. Login accounts and roles were preserved."); } catch (error) { Alert.alert("Cleanup failed", error instanceof Error ? error.message : "Unexpected error."); } finally { setCleaning(false); } }
  return <ScrollView contentContainerStyle={styles.content}><View style={styles.info}><Text style={styles.infoTitle}>Security</Text><Text style={styles.infoText}>Roles are enforced in both the native interface and Supabase row-level security. Service credentials remain on the server.</Text></View><View style={styles.danger}><Text style={styles.dangerTitle}>Admin data cleanup</Text><Text style={styles.description}>Remove all operating data for {profile?.organizationName}. This action cannot be undone.</Text><TextInput autoCapitalize="characters" onChangeText={setConfirmation} placeholder="Type CLEANUP" placeholderTextColor={colors.muted} style={styles.input} value={confirmation} /><Pressable disabled={cleaning} onPress={confirmCleanup} style={[styles.delete, cleaning && styles.disabled]}><Text style={styles.deleteText}>{cleaning ? "Cleaning…" : "Cleanup club data"}</Text></Pressable></View></ScrollView>;
}
const styles = StyleSheet.create({ content: { padding: 18, backgroundColor: colors.background }, info: { padding: 17, borderWidth: 1, borderColor: colors.line, borderRadius: 15, backgroundColor: colors.surface }, infoTitle: { color: colors.ink, fontSize: 18, fontWeight: "900" }, infoText: { marginTop: 7, color: colors.muted, lineHeight: 21 }, danger: { marginTop: 18, padding: 17, borderWidth: 1, borderColor: "#FDA4AF", borderRadius: 15, backgroundColor: "#FFF1F2" }, dangerTitle: { color: colors.danger, fontSize: 18, fontWeight: "900" }, description: { marginTop: 7, color: colors.ink, lineHeight: 21 }, input: { minHeight: 50, marginTop: 15, paddingHorizontal: 13, color: colors.ink, borderWidth: 1, borderColor: "#FDA4AF", borderRadius: 11, backgroundColor: "white" }, delete: { minHeight: 50, marginTop: 10, alignItems: "center", justifyContent: "center", borderRadius: 11, backgroundColor: colors.danger }, deleteText: { color: "white", fontWeight: "900" }, disabled: { opacity: 0.5 } });
