import { useCallback, useMemo, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect } from "@react-navigation/native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { useAuth } from "../auth/AuthProvider";
import { LoadingView } from "../components/LoadingView";
import { SelectModal } from "../components/SelectModal";
import { mobileApi } from "../lib/api";
import { supabase } from "../lib/supabase";
import type { RootStackParamList } from "../navigation/types";
import { colors } from "../theme";

type Player = { id: string; name: string; status?: string };
type Team = { key: string; id?: string; name: string; captainPlayerId: string; playerIds: string[] };
type Picker = { teamIndex: number; type: "captain" | "player" };
export function TeamsScreen({ route }: NativeStackScreenProps<RootStackParamList, "Teams">) {
  const { profile } = useAuth(); const [players, setPlayers] = useState<Player[]>([]); const [teams, setTeams] = useState<Team[]>([]); const [playersPerTeam, setPlayersPerTeam] = useState("8"); const [picker, setPicker] = useState<Picker | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); const { data, error: queryError } = await supabase.rpc("public_session_team_builder", { p_session_id: route.params.sessionId }); if (queryError) setError(queryError.message); else { const payload = data as any; setPlayers(payload?.players ?? []); setPlayersPerTeam(String(payload?.settings?.playersPerTeam ?? payload?.draft?.playersPerTeam ?? 8)); const existing = payload?.teams ?? []; setTeams(existing.length ? existing.map((team: any) => ({ key: team.id, id: team.id, name: team.name, captainPlayerId: team.captainPlayerId ?? "", playerIds: (team.players ?? []).map((player: any) => player.id) })) : [newTeam(1), newTeam(2)]); } setLoading(false); }, [route.params.sessionId]); useFocusEffect(useCallback(() => { void load(); }, [load]));
  const assigned = useMemo(() => new Set(teams.flatMap((team) => team.playerIds)), [teams]); const options = useMemo(() => { if (!picker) return []; if (picker.type === "captain") return [{ value: "", label: "No captain" }, ...players.map((player) => ({ value: player.id, label: player.name }))]; return players.filter((player) => !assigned.has(player.id)).map((player) => ({ value: player.id, label: `${player.name}${player.status === "waitlisted" ? " · Waitlisted" : ""}` })); }, [assigned, picker, players]); if (loading) return <LoadingView error={error} />;
  function patchTeam(index: number, patch: Partial<Team>) { setTeams((current) => current.map((team, teamIndex) => teamIndex === index ? { ...team, ...patch } : team)); }
  function addPlayer(index: number, playerId: string) { patchTeam(index, { playerIds: [...teams[index].playerIds, playerId] }); }
  function removePlayer(index: number, playerId: string) { const team = teams[index]; patchTeam(index, { playerIds: team.playerIds.filter((id) => id !== playerId), captainPlayerId: team.captainPlayerId === playerId ? "" : team.captainPlayerId }); }
  async function save() { if (!profile) return; if (teams.some((team) => !team.name.trim())) return Alert.alert("Missing team name", "Every team needs a name."); setSaving(true); try { await mobileApi("/sessions", { method: "POST", body: JSON.stringify({ organizationId: profile.organizationId, sessionId: route.params.sessionId, action: "save_teams", data: { playersPerTeam: Math.max(1, Number(playersPerTeam) || 8), teams: teams.map((team) => ({ id: team.id, name: team.name.trim(), captainPlayerId: team.captainPlayerId || null, playerIds: team.playerIds })) } }) }); await load(); Alert.alert("Saved", "Teams and player assignments were saved."); } catch (saveError) { Alert.alert("Could not save teams", saveError instanceof Error ? saveError.message : "Unexpected error."); } finally { setSaving(false); } }
  return <ScrollView contentContainerStyle={styles.content}><View style={styles.header}><View style={styles.headerText}><Text style={styles.heading}>Team builder</Text><Text style={styles.intro}>{assigned.size} of {players.length} available players assigned</Text></View><View><Text style={styles.smallLabel}>Players/team</Text><TextInput keyboardType="number-pad" onChangeText={setPlayersPerTeam} style={styles.capacity} value={playersPerTeam} /></View></View>{error ? <Text style={styles.error}>{error}</Text> : null}{teams.map((team, index) => <View key={team.key} style={styles.team}><View style={styles.teamHeader}><TextInput onChangeText={(name) => patchTeam(index, { name })} style={styles.teamName} value={team.name} /><Pressable disabled={teams.length <= 2} onPress={() => setTeams((current) => current.filter((_, teamIndex) => teamIndex !== index))}><Text style={styles.removeTeam}>Delete</Text></Pressable></View><Pressable onPress={() => setPicker({ teamIndex: index, type: "captain" })} style={styles.captain}><Text style={styles.smallLabel}>Captain</Text><Text style={styles.captainName}>{playerName(players, team.captainPlayerId) ?? "Select captain"} ›</Text></Pressable>{team.playerIds.map((playerId) => <View key={playerId} style={styles.player}><Text style={styles.playerName}>{playerName(players, playerId) ?? "Unknown player"}{team.captainPlayerId === playerId ? " · Captain" : ""}</Text><Pressable onPress={() => removePlayer(index, playerId)}><Text style={styles.remove}>Remove</Text></Pressable></View>)}<Pressable disabled={assigned.size >= players.length || team.playerIds.length >= Number(playersPerTeam)} onPress={() => setPicker({ teamIndex: index, type: "player" })} style={styles.addPlayer}><Text style={styles.addPlayerText}>+ Add player</Text></Pressable></View>)}<Pressable onPress={() => setTeams((current) => [...current, newTeam(current.length + 1)])} style={styles.addTeam}><Text style={styles.addTeamText}>+ Add team</Text></Pressable><Pressable disabled={saving} onPress={() => void save()} style={[styles.save, saving && styles.disabled]}><Text style={styles.saveText}>{saving ? "Saving…" : "Save teams"}</Text></Pressable><SelectModal onChange={(value) => { if (!picker) return; if (picker.type === "captain") { const team = teams[picker.teamIndex]; patchTeam(picker.teamIndex, { captainPlayerId: value, playerIds: value && !team.playerIds.includes(value) ? [...team.playerIds, value] : team.playerIds }); } else addPlayer(picker.teamIndex, value); }} onClose={() => setPicker(null)} options={options} title={picker?.type === "captain" ? "Select captain" : "Add player"} value={picker?.type === "captain" ? teams[picker.teamIndex]?.captainPlayerId : ""} visible={picker !== null} /></ScrollView>;
}
function newTeam(number: number): Team { return { key: `new-${Date.now()}-${number}`, name: `Team ${number}`, captainPlayerId: "", playerIds: [] }; } function playerName(players: Player[], id: string) { return players.find((player) => player.id === id)?.name ?? null; }
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 44, backgroundColor: colors.background }, header: { flexDirection: "row", gap: 14, alignItems: "center" }, headerText: { flex: 1 }, heading: { color: colors.ink, fontSize: 24, fontWeight: "900" }, intro: { marginTop: 5, color: colors.muted }, smallLabel: { color: colors.muted, fontSize: 10, fontWeight: "900", textTransform: "uppercase" }, capacity: { width: 70, minHeight: 42, marginTop: 4, textAlign: "center", color: colors.ink, borderWidth: 1, borderColor: colors.line, borderRadius: 9, backgroundColor: colors.surface }, error: { marginTop: 10, color: colors.danger }, team: { marginTop: 15, padding: 15, borderWidth: 1, borderColor: colors.line, borderRadius: 15, backgroundColor: colors.surface }, teamHeader: { flexDirection: "row", alignItems: "center", gap: 10 }, teamName: { flex: 1, minHeight: 46, paddingHorizontal: 11, color: colors.ink, fontSize: 17, fontWeight: "900", borderWidth: 1, borderColor: colors.line, borderRadius: 9 }, removeTeam: { color: colors.danger, fontWeight: "800" }, captain: { marginTop: 10, padding: 10, borderRadius: 9, backgroundColor: colors.pitchSoft }, captainName: { marginTop: 3, color: colors.pitch, fontWeight: "900" }, player: { minHeight: 45, marginTop: 8, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", borderWidth: 1, borderColor: colors.line, borderRadius: 9 }, playerName: { flex: 1, color: colors.ink, fontWeight: "700" }, remove: { color: colors.danger, fontSize: 12, fontWeight: "800" }, addPlayer: { marginTop: 9, paddingVertical: 10, alignItems: "center", borderRadius: 9, backgroundColor: "#F1F5F9" }, addPlayerText: { color: colors.pitch, fontWeight: "900" }, addTeam: { marginTop: 15, minHeight: 48, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.pitch, borderRadius: 10 }, addTeamText: { color: colors.pitch, fontWeight: "900" }, save: { minHeight: 52, marginTop: 12, alignItems: "center", justifyContent: "center", borderRadius: 11, backgroundColor: colors.pitch }, saveText: { color: "white", fontSize: 16, fontWeight: "900" }, disabled: { opacity: 0.5 } });
