import { useCallback, useState } from "react";
import { Alert, FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect } from "@react-navigation/native";
import { useAuth } from "../auth/AuthProvider";
import { LoadingView } from "../components/LoadingView";
import { SelectModal } from "../components/SelectModal";
import { mobileApi } from "../lib/api";
import { supabase } from "../lib/supabase";
import { colors } from "../theme";

type Member = { id: string; role: string; player_id: string | null; profiles: any };
type Player = { id: string; display_name: string };
export function UsersScreen() {
  const { profile } = useAuth(); const [members, setMembers] = useState<Member[]>([]); const [players, setPlayers] = useState<Player[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async (refresh = false) => { if (!profile) return; refresh ? setRefreshing(true) : setLoading(true); const [memberResult, playerResult] = await Promise.all([supabase.from("organization_members").select("id,role,player_id,profiles(id,display_name,email)").eq("organization_id", profile.organizationId).order("created_at"), supabase.from("players").select("id,display_name").eq("organization_id", profile.organizationId).order("display_name")]); const firstError = memberResult.error ?? playerResult.error; if (firstError) setError(firstError.message); else { setMembers((memberResult.data ?? []) as Member[]); setPlayers(playerResult.data ?? []); } setLoading(false); setRefreshing(false); }, [profile]);
  useFocusEffect(useCallback(() => { void load(); }, [load])); if (loading) return <LoadingView error={error} />;
  return <FlatList contentContainerStyle={styles.content} data={members} keyExtractor={(item) => item.id} refreshControl={<RefreshControl onRefresh={() => void load(true)} refreshing={refreshing} tintColor={colors.pitch} />} ListHeaderComponent={<View><Text style={styles.heading}>Organization users</Text><Text style={styles.intro}>Map login accounts to players and control role-based access.</Text>{error ? <Text style={styles.error}>{error}</Text> : null}</View>} renderItem={({ item }) => <UserCard member={item} organizationId={profile!.organizationId} players={players} onSaved={() => load(true)} />} />;
}

function UserCard({ member, players, organizationId, onSaved }: { member: Member; players: Player[]; organizationId: string; onSaved(): Promise<void> }) {
  const account = Array.isArray(member.profiles) ? member.profiles[0] : member.profiles; const [role, setRole] = useState(member.role); const [playerId, setPlayerId] = useState(member.player_id ?? ""); const [password, setPassword] = useState(""); const [selecting, setSelecting] = useState<"role" | "player" | null>(null); const [saving, setSaving] = useState(false);
  const options = selecting === "role" ? ["owner", "admin", "captain", "player"].map((value) => ({ value, label: title(value) })) : [{ value: "", label: "No player mapping" }, ...players.map((player) => ({ value: player.id, label: player.display_name }))];
  async function updateUser() { setSaving(true); try { await mobileApi("/admin", { method: "POST", body: JSON.stringify({ organizationId, action: "update_user", data: { member_id: member.id, role, player_id: playerId || null } }) }); await onSaved(); Alert.alert("Saved", "User access was updated."); } catch (error) { Alert.alert("Could not update user", message(error)); } finally { setSaving(false); } }
  async function updatePassword() { if (password.length < 6) return Alert.alert("Invalid password", "Password must contain at least 6 characters."); setSaving(true); try { await mobileApi("/admin", { method: "POST", body: JSON.stringify({ organizationId, action: "update_password", data: { member_id: member.id, password } }) }); setPassword(""); Alert.alert("Saved", "Password was changed."); } catch (error) { Alert.alert("Could not update password", message(error)); } finally { setSaving(false); } }
  return <View style={styles.card}><Text style={styles.name}>{account?.display_name ?? "Unnamed user"}</Text><Text style={styles.email}>{account?.email ?? "No email"}</Text><Pressable onPress={() => setSelecting("role")} style={styles.select}><Text style={styles.selectLabel}>Role</Text><Text style={styles.selectValue}>{title(role)} ›</Text></Pressable><Pressable onPress={() => setSelecting("player")} style={styles.select}><Text style={styles.selectLabel}>Player</Text><Text style={styles.selectValue}>{players.find((player) => player.id === playerId)?.display_name ?? "No mapping"} ›</Text></Pressable><Pressable disabled={saving} onPress={() => void updateUser()} style={styles.primary}><Text style={styles.primaryText}>{saving ? "Saving…" : "Save access"}</Text></Pressable><View style={styles.passwordRow}><TextInput autoCapitalize="none" onChangeText={setPassword} placeholder="New password" placeholderTextColor={colors.muted} secureTextEntry style={styles.password} value={password} /><Pressable disabled={saving || !password} onPress={() => void updatePassword()} style={styles.secondary}><Text style={styles.secondaryText}>Change</Text></Pressable></View><SelectModal onChange={(value) => selecting === "role" ? setRole(value) : setPlayerId(value)} onClose={() => setSelecting(null)} options={options} title={selecting === "role" ? "Select role" : "Map player"} value={selecting === "role" ? role : playerId} visible={selecting !== null} /></View>;
}
function title(value: string) { return value.replace(/\b\w/g, (letter) => letter.toUpperCase()); } function message(error: unknown) { return error instanceof Error ? error.message : "Unexpected error."; }
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 40, backgroundColor: colors.background }, heading: { color: colors.ink, fontSize: 26, fontWeight: "900" }, intro: { marginTop: 6, marginBottom: 16, color: colors.muted }, error: { marginBottom: 12, color: colors.danger }, card: { marginBottom: 12, padding: 16, borderWidth: 1, borderColor: colors.line, borderRadius: 15, backgroundColor: colors.surface }, name: { color: colors.ink, fontSize: 17, fontWeight: "900" }, email: { marginTop: 3, marginBottom: 12, color: colors.muted }, select: { minHeight: 49, marginBottom: 9, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderWidth: 1, borderColor: colors.line, borderRadius: 10 }, selectLabel: { color: colors.muted, fontSize: 12, fontWeight: "800" }, selectValue: { color: colors.ink, fontWeight: "800" }, primary: { minHeight: 45, alignItems: "center", justifyContent: "center", borderRadius: 10, backgroundColor: colors.pitch }, primaryText: { color: "white", fontWeight: "900" }, passwordRow: { marginTop: 14, flexDirection: "row", gap: 8 }, password: { flex: 1, minHeight: 45, paddingHorizontal: 12, color: colors.ink, borderWidth: 1, borderColor: colors.line, borderRadius: 10 }, secondary: { paddingHorizontal: 14, alignItems: "center", justifyContent: "center", borderRadius: 10, backgroundColor: colors.pitchSoft }, secondaryText: { color: colors.pitch, fontWeight: "900" } });
