import { useCallback, useState } from "react";
import { Alert, StyleSheet, Text, View } from "react-native";
import { useFocusEffect } from "@react-navigation/native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { useAuth } from "../auth/AuthProvider";
import { LoadingView } from "../components/LoadingView";
import { VoiceScoringPanel, type ParsedVoiceGoal } from "../components/VoiceScoringPanel";
import { mobileApi } from "../lib/api";
import { supabase } from "../lib/supabase";
import type { RootStackParamList } from "../navigation/types";
import { colors } from "../theme";

export function VoiceScoresScreen({ route, navigation }: NativeStackScreenProps<RootStackParamList, "VoiceScores">) {
  const { profile } = useAuth(); const [payload, setPayload] = useState<any>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); const { data, error: queryError } = await supabase.rpc("public_game_score_editor", { p_session_id: route.params.sessionId }); if (queryError) setError(queryError.message); else setPayload(data); setLoading(false); }, [route.params.sessionId]); useFocusEffect(useCallback(() => { void load(); }, [load])); if (loading) return <LoadingView error={error} />;
  const teams = payload?.teams ?? []; const matches = payload?.matches ?? []; const context = { matches: matches.map((match: any) => ({ matchNumber: match.matchNumber, teams: [match.teamAId, match.teamBId].map((teamId) => { const team = teams.find((item: any) => item.id === teamId); return { name: team?.name ?? "Team", players: (team?.players ?? []).map((player: any) => player.name) }; }) })) };
  async function apply(goals: ParsedVoiceGoal[]) { if (!profile || saving) return; const unresolved: string[] = []; const games = matches.map((match: any) => { const additions = goals.filter((goal) => goal.matchNumber === match.matchNumber).flatMap((goal) => { const scorer = findPlayer(teams, goal.scorerName); if (!scorer) { unresolved.push(goal.scorerName); return []; } const assist = goal.assistName ? findPlayer(teams, goal.assistName) : null; return [{ key: randomKey(), scorerId: scorer.id, assistPlayerId: assist?.id ?? "", goalType: goal.goalType === "own_goal" ? "own_goal" : "goal", goalCount: Math.max(1, Number(goal.goalCount ?? 1)) }]; }); return { key: match.id, matchNumber: match.matchNumber, displayOrder: match.displayOrder, matchType: match.matchType, teamAId: match.teamAId, teamBId: match.teamBId, awayTeamId: match.awayTeamId ?? "", resultStatus: additions.length ? "played" : match.resultStatus, scheduledStartTime: match.scheduledStartTime ?? "", scheduledEndTime: match.scheduledEndTime ?? "", goals: [...(match.goals ?? []).map((goal: any) => ({ key: goal.id, scorerId: goal.scorerId, assistPlayerId: goal.assistPlayerId ?? "", goalType: goal.goalType, goalCount: goal.goalCount ?? 1 })), ...additions] }; }); if (unresolved.length) return Alert.alert("Player not matched", `Could not match: ${Array.from(new Set(unresolved)).join(", ")}. Edit the transcript and try again.`); setSaving(true); try { await mobileApi("/sessions", { method: "POST", body: JSON.stringify({ organizationId: profile.organizationId, sessionId: route.params.sessionId, action: "save_scores", data: { games } }) }); Alert.alert("Saved", "Voice goals were added to the game scores."); navigation.goBack(); } catch (saveError) { Alert.alert("Could not save", saveError instanceof Error ? saveError.message : "Unexpected error."); } finally { setSaving(false); } }
  return <View style={styles.page}><Text style={styles.heading}>{payload?.session?.name ?? payload?.session?.sessionDate ?? "Voice scoring"}</Text>{error ? <Text style={styles.error}>{error}</Text> : null}{matches.length ? <VoiceScoringPanel context={context} onApply={(goals) => void apply(goals)} sessionId={route.params.sessionId} /> : <Text style={styles.empty}>Generate a fixture before recording scores.</Text>}{saving ? <Text style={styles.saving}>Saving voice goals…</Text> : null}</View>;
}
function findPlayer(teams: any[], name: string) { const target = normalize(name); const players = teams.flatMap((team) => team.players ?? []); return players.find((player: any) => normalize(player.name) === target) ?? players.find((player: any) => normalize(player.name).includes(target) || target.includes(normalize(player.name))); } function normalize(value: string) { return value.toLowerCase().replace(/[^a-z0-9]/g, ""); } function randomKey() { return `${Date.now()}-${Math.random().toString(36).slice(2)}`; }
const styles = StyleSheet.create({ page: { flex: 1, padding: 16, backgroundColor: colors.background }, heading: { color: colors.ink, fontSize: 24, fontWeight: "900" }, error: { marginTop: 8, color: colors.danger }, empty: { marginTop: 20, color: colors.muted }, saving: { marginTop: 12, color: colors.pitch, fontWeight: "900" } });
