import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput } from "react-native";
import { useAuth } from "../auth/AuthProvider";
import { SelectModal, type SelectOption } from "../components/SelectModal";
import { mobileApi } from "../lib/api";
import { supabase } from "../lib/supabase";
import { colors } from "../theme";

export function WaiverScreen({ navigation }: any) {
  const { profile, activeProgram } = useAuth(); const [sessions, setSessions] = useState<SelectOption[]>([]); const [players, setPlayers] = useState<SelectOption[]>([]); const [sessionId, setSessionId] = useState(""); const [playerId, setPlayerId] = useState(""); const [amount, setAmount] = useState(""); const [reason, setReason] = useState(""); const [selecting, setSelecting] = useState<"session" | "player" | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!profile) return; let sq: any = supabase.from("sessions").select("id,name,session_date").eq("organization_id", profile.organizationId).order("session_date", { ascending: false }); if (activeProgram?.id) sq = sq.eq("program_id", activeProgram.id); void Promise.all([sq, supabase.from("players").select("id,display_name").eq("organization_id", profile.organizationId).eq("status", "active").order("display_name")]).then(([sr, pr]) => { setSessions((sr.data ?? []).map((r: any) => ({ value: r.id, label: `${r.session_date} · ${r.name ?? "Session"}` }))); setPlayers((pr.data ?? []).map((r: any) => ({ value: r.id, label: r.display_name }))); }); }, [activeProgram?.id, profile]);
  const options = selecting === "session" ? sessions : players; const value = selecting === "session" ? sessionId : playerId; const label = (items: SelectOption[], id: string) => items.find((item) => item.value === id)?.label ?? "Select";
  async function save() { if (!profile || !sessionId || !playerId || amount === "") return Alert.alert("Missing information", "Session, player, and waiver amount are required."); const parsed = Number(amount); if (!Number.isFinite(parsed) || parsed < 0) return Alert.alert("Invalid amount", "Enter zero or a positive amount."); if (parsed > 0 && !reason.trim()) return Alert.alert("Missing reason", "A reason is required."); setSaving(true); try { await mobileApi("/admin", { method: "POST", body: JSON.stringify({ organizationId: profile.organizationId, action: "apply_waiver", data: { sessionId, playerId, waiverAmount: parsed, waiverReason: reason } }) }); Alert.alert("Waiver saved", parsed > 0 ? "The charge and ledger were updated." : "The waiver was removed."); navigation.goBack(); } catch (e) { Alert.alert("Could not save waiver", e instanceof Error ? e.message : "Unexpected error."); } finally { setSaving(false); } }
  return <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.intro}>Apply a waiver to confirmed, played, or replacement attendance. Enter 0 to remove one.</Text><Pressable onPress={() => setSelecting("session")} style={styles.select}><Text style={styles.label}>Session</Text><Text style={styles.value}>{label(sessions, sessionId)}</Text></Pressable><Pressable onPress={() => setSelecting("player")} style={styles.select}><Text style={styles.label}>Player</Text><Text style={styles.value}>{label(players, playerId)}</Text></Pressable><Text style={styles.label}>Waiver amount</Text><TextInput keyboardType="decimal-pad" onChangeText={setAmount} style={styles.input} value={amount} /><Text style={styles.label}>Reason</Text><TextInput multiline onChangeText={setReason} style={[styles.input, styles.notes]} value={reason} /><Pressable disabled={saving} onPress={() => void save()} style={styles.button}><Text style={styles.buttonText}>{saving ? "Saving…" : "Save waiver"}</Text></Pressable><SelectModal onChange={(next) => selecting === "session" ? setSessionId(next) : setPlayerId(next)} onClose={() => setSelecting(null)} options={options} title={`Select ${selecting ?? "option"}`} value={value} visible={selecting !== null} /></ScrollView>;
}
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 44, backgroundColor: colors.background }, intro: { marginBottom: 18, color: colors.muted, lineHeight: 20 }, select: { marginBottom: 13, padding: 14, borderWidth: 1, borderColor: colors.line, borderRadius: 12, backgroundColor: colors.surface }, label: { marginTop: 5, marginBottom: 6, color: colors.ink, fontSize: 12, fontWeight: "800", textTransform: "uppercase" }, value: { color: colors.muted }, input: { minHeight: 50, marginBottom: 13, paddingHorizontal: 14, color: colors.ink, borderWidth: 1, borderColor: colors.line, borderRadius: 12, backgroundColor: colors.surface }, notes: { minHeight: 96, paddingTop: 14, textAlignVertical: "top" }, button: { minHeight: 52, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: colors.pitch }, buttonText: { color: "white", fontWeight: "900" } });
