import { z } from "zod";
import { leagueSchema, leagueTeamSchema } from "@/lib/schemas";
import { authenticateMobileRequest, mobileApiErrorResponse, requireMobileRole } from "@/lib/supabase/mobile-api";

const inputSchema = z.object({ organizationId: z.string().uuid(), action: z.enum(["create", "save_team", "generate_fixtures", "save_result"]), data: z.record(z.string(), z.unknown()) });
export async function POST(request: Request) {
  try {
    const input = inputSchema.parse(await request.json()); const { supabase, actor } = await authenticateMobileRequest(request, input.organizationId); requireMobileRole(actor, ["admin"]);
    if (input.action === "create") { const parsed = leagueSchema.parse(input.data); const slug = await uniqueSlug(supabase, actor.organizationId, parsed.name); const { data, error } = await supabase.from("leagues").insert({ ...parsed, slug, organization_id: actor.organizationId, created_by: actor.profileId }).select("id").single(); if (error) throw new Error(error.message); return Response.json({ ok: true, id: data.id }); }
    if (input.action === "save_team") { const parsed = leagueTeamSchema.parse(input.data); const { data: league, error: leagueError } = await supabase.from("leagues").select("id").eq("id", parsed.league_id).eq("organization_id", actor.organizationId).maybeSingle(); if (leagueError || !league) throw new Error(leagueError?.message ?? "League not found."); const { data: team, error } = await supabase.from("league_teams").upsert({ organization_id: actor.organizationId, league_id: parsed.league_id, name: parsed.name, captain_player_id: parsed.captain_player_id, seed_order: parsed.seed_order, created_by: actor.profileId }, { onConflict: "league_id,name" }).select("id").single(); if (error) throw new Error(error.message); const { error: deleteError } = await supabase.from("league_team_players").delete().eq("league_team_id", team.id); if (deleteError) throw new Error(deleteError.message); if (parsed.player_ids.length) { const { error: playerError } = await supabase.from("league_team_players").insert(parsed.player_ids.map((playerId) => ({ organization_id: actor.organizationId, league_id: parsed.league_id, league_team_id: team.id, player_id: playerId, created_by: actor.profileId }))); if (playerError) throw new Error(playerError.message); } return Response.json({ ok: true, id: team.id }); }
    if (input.action === "generate_fixtures") { const { leagueId } = z.object({ leagueId: z.string().uuid() }).parse(input.data); const { data: teams, error } = await supabase.from("league_teams").select("id").eq("league_id", leagueId).eq("organization_id", actor.organizationId).order("seed_order", { ascending: true, nullsFirst: false }).order("name"); if (error) throw new Error(error.message); if (!teams || teams.length < 2) throw new Error("Add at least two teams before generating fixtures."); const fixtures = roundRobin(teams.map((team) => team.id)).map((fixture, index) => ({ organization_id: actor.organizationId, league_id: leagueId, match_number: index + 1, round_number: fixture.round, status: "scheduled", team_a_id: fixture.teamAId, team_b_id: fixture.teamBId, created_by: actor.profileId })); const { error: deleteError } = await supabase.from("league_matches").delete().eq("league_id", leagueId).eq("organization_id", actor.organizationId); if (deleteError) throw new Error(deleteError.message); const { error: insertError } = await supabase.from("league_matches").insert(fixtures); if (insertError) throw new Error(insertError.message); await supabase.from("leagues").update({ status: "active" }).eq("id", leagueId).eq("organization_id", actor.organizationId); return Response.json({ ok: true, fixtures: fixtures.length }); }
    const parsed = z.object({ leagueId: z.string().uuid(), matchId: z.string().uuid(), teamAScore: z.number().int().nonnegative(), teamBScore: z.number().int().nonnegative() }).parse(input.data); const { error } = await supabase.from("league_matches").update({ status: "completed", team_a_score: parsed.teamAScore, team_b_score: parsed.teamBScore }).eq("id", parsed.matchId).eq("league_id", parsed.leagueId).eq("organization_id", actor.organizationId); if (error) throw new Error(error.message); return Response.json({ ok: true });
  } catch (error) { return mobileApiErrorResponse(error); }
}

async function uniqueSlug(supabase: any, organizationId: string, name: string) { const base = name.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "league"; for (let suffix = 1; suffix < 100; suffix += 1) { const slug = suffix === 1 ? base : `${base}-${suffix}`; const { data } = await supabase.from("leagues").select("id").eq("organization_id", organizationId).eq("slug", slug).maybeSingle(); if (!data) return slug; } throw new Error("Could not create a unique league slug."); }
function roundRobin(teamIds: string[]) { const teams = [...teamIds]; if (teams.length % 2) teams.push(""); const fixtures: Array<{ round: number; teamAId: string; teamBId: string }> = []; for (let round = 1; round < teams.length; round += 1) { for (let index = 0; index < teams.length / 2; index += 1) { const a = teams[index]; const b = teams[teams.length - 1 - index]; if (a && b) fixtures.push(round % 2 === 0 ? { round, teamAId: b, teamBId: a } : { round, teamAId: a, teamBId: b }); } teams.splice(1, 0, teams.pop()!); } return fixtures; }
